package constant

const (
	Patient                 = "/registration"
	PatientInfo             = "/patient-info"
	SinglePatient           = "/patient-info/:patient_id"
	PatientRegistration     = "/patient-registration"
	PatientPrescription     = "/patient-prescription"
	PrescriptionByPatientId = "/patient-prescription/:patient_id"
	AllPrescription         = "/get-prescription"
	UpdatePrescription      = "/patient-prescription/:prescription_id"
	User                    = "/getuser"
	Disease                 = "/get-disease/:disease_id"
	AllDisease              = "/get-disease"
	AddDisease              = "/add-disease"
	Cause                   = "/causes"
	Symptom                 = "/symptom"
	AddSymptom              = "/add-symptom"
	UpdateSymptom           = "/update-symptom"
	AddCause                = "/add-cause"
	UpdateCause             = "/update-cause"
	DiseaseProfile          = "/disease-profile"
	DiagnosticTests         = "/diagnostic-tests"
	Medication              = "/get-medication"
	AddMedication           = "/add-medication"
	// UpdateMedication    = "/update-medication/:medication_id"
	UpdateMedication                = "/update-medication"
	DiagnosticTest                  = "/diagnostic-test"
	SingleDiagnosticTest            = "/diagnostic-test/:diagnosticTestId"
	DiagnosticComponents            = "/diagnostic-components"
	DiagnosticComponent             = "/diagnostic-component"
	SingleDiagnosticComponent       = "/diagnostic-component/:diagnosticComponentId"
	DiagnosticTestComponentMappings = "/diagnostic-test-component-mappings"
	DiagnosticTestComponentMapping  = "/diagnostic-test-component-mapping"

	Exercise       = "/add-exercise"
	AllExercise    = "/get-exercise"
	SingleExercise = "/exercise/:exercise_id"
	UpdateExercise = "/update-exercise/:exercise_id"

	Diet            = "/add-template"
	AllDietTemplate = "/diet-template"
	SingleDiet      = "/diet-template/:diet_id"
	UpdateDiet      = "/update-diet/:diet_id"
)

const (
	Success = "success"
	Failure = "failure"
)
